device: cuda
# model configuration
model:
  name: Unet2D

# training configuration
train:
  batch_size: 6
  epoch: 600
  learning_rate: 0.01
  project_path: C:\Users\test\Desktop\Leon\Projects\Breast_Ultrasound
  checkpoint_saving_steps: 100

# trainer configuration

# optimizer configuration

# loss function configuration
# dataset configuration
dataset:
  # data_path: C:\Users\test\Desktop\Leon\Datasets\Kaggle_Breast_Ultraound\archive\Dataset_BUSI_with_GT
  data_path: C:\Users\test\Desktop\Leon\Datasets\Kaggle_Breast_Ultraound\Kaggle_BU_aug
  data_split: 
    - 0.7
    - 0.3
  shuffle: True
  dir_key: ""
  file_key: mask
  preprocess_config:
    crop_size: 
      - 512
      - 512
    PadToSquare: False
    HorizontalFlip: False
    RandCrop: False
    RandScale: False
    ScaleToSize: False
    ScaleLimitSize: False
    padding_height: 512
    padding_width: 512
    padding_value: 0.0
    flip_prob: 0.5
    min_scale_factor: 1.0
    max_scale_factor: 1.25
    step_size: 0.125
    resize_method: Bilinear
    flip_prob: 0.5
    scale_size: 
      - 512
      - 512
  
  

