device: cuda
# model configuration
model:
  name: Unet2D
  output_strides: 16
  in_channels: 1
  out_channels: 1
# training configuration
# train:
#   batch_size: 1
#   epoch: 300
#   learning_rate: 0.01
#   project_path: C:\Users\test\Desktop\Leon\Projects\Breast_Ultrasound
#   checkpoint_saving_steps: 50

# trainer configuration

# optimizer configuration

# loss function configuration
# dataset configuration
  
aug_samples:
  crop: True
  flip: True
  scale: True
  crop_size: 512

dataset:
  data_path: C:\Users\test\Desktop\Leon\Datasets\Kaggle_Breast_Ultraound\archive\Dataset_BUSI_with_GT
  index_path: C:\Users\test\Desktop\Leon\Projects\Breast_Ultrasound\dataset\index
  data_split: 
    - 0.7
    - 0.3
  train:
    shuffle: False
    dir_key: "benign"
    file_key: mask
    is_data_augmentation: False
    preprocess_config:
      crop_size: 
        - 512
        - 512
      # PadToSquare: False
      HorizontalFlip: True
      RandCrop: True
      RandScale: False
      # ScaleToSize: False
      # ScaleLimitSize: True
      RandRotate: True
      GaussianBlur: True
      padding_value: 0.0
      flip_prob: 0.5
      min_scale_factor: 1.0
      max_scale_factor: 1.25
      step_size: 0.125
      min_resize_value: 384
      max_resize_value: 512
      scale_factor_step_size: 32
      resize_method: Bilinear
      flip_prob: 0.5
      min_angle: -45
      max_angle: 45
      show_preprocess: False
  val:
    shuffle: False
    dir_key: "benign"
    file_key: mask
    is_data_augmentation: True
    preprocess_config:
      crop_size: 
        - 512
        - 512
      # PadToSquare: False
      HorizontalFlip: True
      RandCrop: True
      RandScale: True
      # ScaleToSize: False
      ScaleLimitSize: True
      RandRotate: True
      GaussianBlur: False
      padding_value: 0.0
      flip_prob: 0.5
      min_scale_factor: 1.0
      max_scale_factor: 1.25
      step_size: 0.125
      min_resize_value: 384
      max_resize_value: 512
      scale_factor_step_size: 32
      resize_method: Bilinear
      flip_prob: 0.5
      min_angle: -45
      max_angle: 45
      show_preprocess: True
  

eval:
  show_segmentation_result: False # TODO: change name
  save_segmentation_result: True
  save_prediciton_only: False
  running_mode: test
  restore_checkpoint_path: C:\Users\test\Desktop\Leon\Projects\Breast_Ultrasound\models\run_040
  checkpoint_name: ckpt_best.pth
  eval_dir_key: benign