device: cuda
# model configuration
# use a fixed random seed to guarantee that when you run the code twice you will get the same outcome
manual_seed: 0
# model configuration
model:
  name: Unet2D
  # model class, e.g. UNet3D, ResidualUNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  # layer_order: gcr
  # feature maps scale factor
  # f_maps: 32
  # number of groups in the groupnorm
  # num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  activation: relu
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  # is_segmentation: true
  output_strides: 16
# training configuration
train:
  epoch: 600
  learning_rate: 0.01
  project_path: C:\Users\test\Desktop\Leon\Projects\Breast_Ultrasound
  checkpoint_saving_steps: 100

# trainer configuration

# optimizer configuration

# loss function configuration
# dataset configuration
dataset:
  data_path: C:\Users\test\Desktop\Leon\Datasets\Kaggle_Breast_Ultraound\archive\Dataset_BUSI_with_GT
  index_path: C:\Users\test\Desktop\Leon\Projects\Breast_Ultrasound\dataset\index
  # data_path: C:\Users\test\Desktop\Leon\Datasets\Kaggle_Breast_Ultraound\Kaggle_BU_aug
  data_split: 
    - 0.7
    - 0.3
  train:
    shuffle: True
    batch_size: 6
    dir_key: ""
    file_key: mask
    is_data_augmentation: True
    preprocess_config:
      crop_size: 
        - 512
        - 512
      # PadToSquare: False
      HorizontalFlip: True
      RandCrop: True
      RandScale: True
      # ScaleToSize: False
      # ScaleLimitSize: True
      RandRotate: True
      GaussianBlur: True
      padding_value: 0.0
      flip_prob: 0.5
      min_scale_factor: 1.0
      max_scale_factor: 1.25
      step_size: 0.125
      min_resize_value: 384
      max_resize_value: 512
      scale_factor_step_size: 32
      resize_method: Bilinear
      flip_prob: 0.5
      min_angle: -45
      max_angle: 45
      show_preprocess: False
  val:
    shuffle: False
    batch_size: 1
    dir_key: ""
    file_key: mask
    is_data_augmentation: False
    preprocess_config:
      crop_size: 
        - 512
        - 512
      # PadToSquare: False
      HorizontalFlip: True
      RandCrop: True
      RandScale: False
      # ScaleToSize: False
      # ScaleLimitSize: True
      RandRotate: True
      GaussianBlur: True
      padding_value: 0.0
      flip_prob: 0.5
      min_scale_factor: 1.0
      max_scale_factor: 1.25
      step_size: 0.125
      min_resize_value: 384
      max_resize_value: 512
      scale_factor_step_size: 32
      resize_method: Bilinear
      flip_prob: 0.5
      min_angle: -45
      max_angle: 45
      show_preprocess: False
  

